sylius_ui:
    events:
        sylius.shop.checkout.select_shipping.before_form:
            blocks:
                scripts:
                    template: "@HubertinioSyliusApaczkaPlugin/_checkout.html.twig"
                    priority: 10