# Delete these routes and define your own shop routes here

hubertinio_sylius_apaczka_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Hubertinio\SyliusApaczkaPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

hubertinio_sylius_apaczka_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Hubertinio\SyliusApaczkaPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
